### ISSUE TITLE
请问您的word2vec.baidubaike.dim300.bin2文件是什么呢

### ISSUE THREAD

**Issue by xuhuilu** [Wu-Jiafeng/KGQA_Intelligent_Manufacturing#1]

**Comment by Wu-Jiafeng** [comment]
你好，word2vec.baidubaike.dim300.bin2是由[中文预训练词向量](https://github.com/Embedding/Chinese-Word-Vectors)（SGNS-百度百科-Word-300d）经[word_vector.py](https://github.com/Wu-Jiafeng/KGQA_Intelligent_Manufacturing/blob/main/BootstrappingRE/data/word_vector.py)所转换的二进制词向量文件。

**Comment by xuhuilu** [comment]
好的，谢谢您，该问题我解决了，因为想复现您的项目，缺少一些文件，请问可以麻烦您提供一下吗？目前在duie数据集方面出了一些问题，我自己找的.jason文件格式有些问题，文件太大我的编辑器修改不了。感谢您！

**Comment by Wu-Jiafeng** [comment]
duie原始文件我也遗失了。。我应该是在duie的[论文](https://arxiv.org/abs/1711.05073)上或者[竞赛](https://aistudio.baidu.com/aistudio/competition/detail/31/0/introduction)上找的，如果文件比较大可以用LogViewer Pro先查看格式再处理一下。
